
const data = {
  products: [
    {
      _id: '1',
      name: 'Sagu Papad',
      category: 'Papad',
      image: '../assets/dalmamasala.JPG',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '2',
      name: 'Lia Badi',
      category: 'Badi',
      image: '/images/p2.jpg',
      price: 100,
      countInStock: 20,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '3',
      name: 'SuperFood',
      category: 'Superfood',
      image: '/images/p3.jpg',
      price: 220,
      countInStock: 0,
      brand: 'Lacoste',
      rating: 4.8,
      numReviews: 17,
      description: 'high quality product',
    },
    {
      _id: '4',
      name: 'Mixture',
      category: 'Mixture',
      image: '/images/p4.jpg',
      price: 78,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      _id: '5',
      name: 'Sweet Mango Pickle',
      category: 'pickle',
      image: 'https://cdn3.mydukaan.io/app/image/140x140/?url=https://dukaan-us.s3.amazonaws.com/4033498/080a44df-54ea-4121-8b31-2898356efb38/bitter-1-4bf69da3-c38e-4d13-93fc-329f1b9bfd06.png',
      price: 65,
      countInStock: 5,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '6',
      name: 'sweet Pickle',
      category: 'Pickle',
      image: 'https://cdn3.mydukaan.io/app/image/140x140/?url=https://dukaan-us.s3.amazonaws.com/4033498/080a44df-54ea-4121-8b31-2898356efb38/garlcc-96ec9ca5-dfef-4e14-83df-0cf431557f7a.png',
      price: 139,
      countInStock: 12,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
  ],
};
export default data;
